### ISSUE TITLE
support v3 api and status of project

### ISSUE THREAD

**Issue by vtolstov** [jdarcy/etcd-api#11]
Do you have any plans to support all v3 stuff? Does this project maintained or you do not have much time for it?
Thanks

**Comment by jdarcy** [comment]
I do not have any particular plans to support v3 stuff.  That doesn't mean I _won't_, only that I don't know if or when I'll find the time.  There's a semi-decent chance that I might do it in a few weeks, when interfacing with etcd again becomes part of $dayjob after a long hiatus.  Of course, if somebody else wanted to provide specific suggestions, or patches, or even take over the project, that would be fine too.

**Comment by vtolstov** [comment]
I think that switch to https://github.com/shafreeck/cetcd , may be best to fix one project. also as i have main idea like in this project =)
