### ISSUE TITLE
using in external software

### ISSUE THREAD

**Issue by vtolstov** [jdarcy/etcd-api#4]
In my software i need to quarantine  that only one instance write in the same time. So i want to use etcd and this library.
So my question is - how can i determine leader? As i understand i need to create key with locking? In key i can set content with current leader name for example?
Or i'm wrong ?

**Comment by edwardcapriolo** [comment]
I guess there are several ways to do it. 

curl http://127.0.0.1:2379/v2/stats/leader

Knowing which etcd server that is the leader however does not help you directly. You still need to develop some type of distributed lock algorithm yourself. You should be able to build on the primitives in this library to build a recipe similar to these : http://curator.apache.org/curator-recipes/index.html let me know if you have any ideas on enhancing the library.

**Comment by jdarcy** [comment]
Sorry for the delayed response.  At the time this library was first implemented, etcd didn't have lock functionality so the project I was working on had to implement its own leader-election protocol (as @edwardcapriolo suggests).  That's in leader.c, with a Murphi model in leader.m for verification.  Later, etcd added compare-and-swap so I added etcd_lock based on that.  For that call, the value is basically meaningless; it's the etcd indices (versions) that matter.  For example:

```
index_in = NULL;
index_out = NULL;
for (;;) {
    /* see etcd-api.h for specific API details */
    res = etcd_lock (session, key, TTL, index_in, &index_out);
    if (res == ETCD_OK) {
        /* we're have the lock (lease) exclusively for TTL seconds */
    }
    /* check for other errors */
    /* free/clear index_out if it was set */
    /* sleep so we don't eat a whole core forever */
}
```

In our case, we just ran this in a separate thread, so other entry points (in other threads) would know whether we're the leader or not.

**Comment by vtolstov** [comment]
@jdarcy Thanks! So when i get lock, other nodes can't get it. But how they determine who is held lock?

**Comment by jdarcy** [comment]
The clean way would be for someone to modify etcd_lock so that unique/meaningful values (e.g. node IDs) can be passed in.  Then anyone else could just use etcd_get to see that.  However, I don't know when I'll be able to get to that.

Failing that, your best bet is probably a protocol using N+2 keys - one for locking, one *per node* for liveness, and one for pointing to a liveness key.  The leader-election part would look something like this:

```
for (;;) {
    /* important to use the same TTL throughout to limit expiration order */
    res = etcd_set (session, my_unique_key, some_value, NULL, TTL);
    res = etcd_lock (session, global_lock, TTL, index_in, index_out);
    if (res == ETCD_OK) {
        /* NB my_unique_key is the *value* for this call */
        res = etcd_set (session, global_pointer_key, my_unique_key, NULL, TTL);
    }
}
```

Then the reader part is like this:

```
maybe_leader = etcd_get (session, global_pointer_key);
if (maybe_leader) {
    /* Ensure that whoever set that is still alive and still leader */
    verify = etcd_get (session, maybe_leader);
    if (verify) {
        /* Valid value; clean up as necessary and return. */
    }
    /* They're dead, with loss of leadership to follow very shortly. */
    /* Delay and retry. */
}
```

I haven't actually verified this solution, but it's a variation on what we used for part of GlusterFS and intuitively seems to avoid the races I know to look for.

**Comment by vtolstov** [comment]
Thanks for info!. Wow etcd api used in Gluster... where i can find info about this?

**Comment by jdarcy** [comment]
Actually etcd is not used in current versions of GlusterFS, but it - or something like it - features in several ongoing sub-projects.  This library was initially developed to support NSR (New Style Replication), as described here:

    http://www.gluster.org/community/documentation/index.php/Features/new-style-replication

Some code that used it is still here:

    http://review.gluster.org/#/c/8913/5/xlators/cluster/nsr-server/src/leader.c

However, that code is pretty stale by now (the project lay dormant for a year) and the etcd-specific parts are effectively stubbed out.  Going forward I'm not sure if we'll actually use etcd or consul or something else (possibly even something home-grown but I hope not).  Whatever it is, it will probably also feature in the 4.0 management overhaul.

    http://www.gluster.org/community/documentation/index.php/Features/thousand-node-glusterd

The people working on other sub-projects have also run into the need for highly consistent and available storage of basic state information.  Without it, we're stuck in a "chicken and egg" situation.  That's kind of the service we ourselves provide, at much higher scale and performance, so relying on it ourselves would create a circular dependency.  By using something external and more self-contained, we can bootstrap our own solutions into existence.  It's kind of like writing the first compiler for a new language.  ;)

**Comment by vtolstov** [comment]
Thanks

**Comment by vtolstov** [comment]
I'm try to understand nsr code, but in my case i have errors that two nodes can do lock in the same time.
```
static void *et_leader_election(void *ignored)
{
  int err;
  char leaderp[MAX_NODE_STR_LEN];
  char lockp[MAX_NODE_STR_LEN];
  char *leader;
  char *verify;
  char npath[MAX_NODE_STR_LEN];
  char            *index_in;
  char            *index_out;

  snprintf(lockp, sizeof(lockp), "%s%s", DEFAULT_BASE, LOCK_NODE);
  snprintf(leaderp, sizeof(leaderp), "%s%s", DEFAULT_BASE, LEADER_NODE);
  sd_info("etcd node alive leader");

  for (;;) {
    index_in = NULL;
    index_out = NULL;

    /* Not leader yet.  Try to become leader. */
    for (;;) {
      if (etcd_lock(et_sess, lockp, NODE_TTL, index_in, &index_out) == ETCD_OK) {
        sd_info("lock success %s %s %s %d", lockp, index_in, index_out, NODE_TTL);
        break;
      }
      sd_info("lock failed");
      sleep(WAIT_TIME);
    }

    if (etcd_set(et_sess, leaderp, id, NULL, NODE_TTL) == ETCD_OK) {
      sd_info("i'm set leader");
      uatomic_set_true(&is_leader);
    } else {
      sd_info("failed to create etcd key %s val %s", leaderp, id);
      continue;
    }

    index_in = index_out;
    index_out = NULL;

    /* Try to retain leadership. */
    for (;;) {
      if (etcd_lock(et_sess, lockp, NODE_TTL, index_in, &index_out) != ETCD_OK) {
        uatomic_set_false(&is_leader);
        sd_info("lost leadership");
        break;
      } else {
        sd_info("lock %s %s %s %d", lockp, index_in, index_out, NODE_TTL);
      }

      if (index_out && (index_in != index_out)) {
        sd_info("YYYYY");
        if (index_in) {
          sd_info("WWWWW");
          free(index_in);
        }
        index_in = index_out;
        index_out = NULL;
      }

      if (etcd_set(et_sess, leaderp, id, NULL, NODE_TTL) != ETCD_OK) {
        sd_info("rrr");
        uatomic_set_false(&is_leader);
        break;
      } else {
        sd_info("EEEE");
      }
      sleep(WAIT_TIME);
    }

    if (index_in) {
      free(index_in);
    }
    if (index_out) {
      free(index_out);
    }
  }
 out:
  err = pthread_detach(pthread_self());
  if (err)
    sd_err("%s", strerror(err));
  pthread_exit(NULL);
}

**Comment by vtolstov** [comment]
first lock in index_out return 404 page not found.

**Comment by vtolstov** [comment]
As i understand something goes in etcd-api wrong.... index_out need to contains index , but in my case 404 error. I'm try to change lock key to sheepdog or something other but it not change index_out.

**Comment by vtolstov** [comment]
Debug output:
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4001 (#0)
> PUT /mod/v2/lock//sheepdog HTTP/1.1
Host: localhost:4001
Accept: */*
Content-Length: 31
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 31 out of 31 bytes
< HTTP/1.1 301 Moved Permanently
< Location: /mod/v2/lock/sheepdog
< Date: Fri, 20 Mar 2015 21:43:11 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:4001/mod/v2/lock/sheepdog'
* Found bundle for host localhost: 0x7fbd98014b50
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 4001 (#0)
> PUT /mod/v2/lock/sheepdog HTTP/1.1
Host: localhost:4001
Accept: */*
Content-Length: 31
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 31 out of 31 bytes
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Date: Fri, 20 Mar 2015 21:43:11 GMT
< Content-Length: 19
<
* Connection #0 to host localhost left intact
Mar 21 00:43:11   INFO [leader_election] et_leader_election(149) lock /sheepdog 404 page not found
```

**Comment by vtolstov** [comment]
Hm.. as i see in etcd 2.x (i'm use 2.0.5) coreos team removed modules so, mod/v2 does not works.
