### ISSUE TITLE
etcd_open / etcd_open_str

### ISSUE THREAD

**Issue by vtolstov** [jdarcy/etcd-api#7]
Why this function does not check url and not try to connect to server?
How i know does connection to server is successful?

**Comment by jdarcy** [comment]
Which function?

**Comment by jdarcy** [comment]
Libcurl is responsible for actually opening connections as needed, and we don't actually have a request for it until someone does e.g. etcd_get.  If you want to do a probe, I suggest using etcd_leader.  The (virtual) key it uses should always exist, so if the system is at all operational then it should work.

**Comment by vtolstov** [comment]
/version key always exists, why not try to get it in etcd_open ? so we don't return valid session if server not responding.
Because now i need to iterate over server list and try to understand does is user provided server responding.

**Comment by jdarcy** [comment]
Why do you need to know if a particular server is responding?  The library will retry across servers automatically, in accordance with the idea that as a group they're equivalent to a single multi-homed server.

**Comment by vtolstov** [comment]
I'm simple need to filter user input to check does it input right. But as i see i don't need that. In the simple case if user provide non working servers my application does not join to cluster.
Can you check issue https://github.com/jdarcy/etcd-api/issues/4 ?
